### ISSUE TITLE
persist is not effective if doas comes after /usr/bin/time.

### ISSUE THREAD

**Issue by amano-kenji** [nholstein/OpenDoas#8]
```
/usr/bin/time doas cmd args...
```

This always prompts for a password. I think doas is confused when it's run as a subprocess.

**Comment by Duncaen** [comment]
Wrong repo, but this works as expected. The persisting authentication is linked to the terminal and parent process since its supposed to be an interactive tool, if you run a command explicitly i.e. `doas id` and then run some other program or script from the same shell, it shouldn't be allowed to blindly run commands with doas.

**Comment by amano-kenji** [comment]
```
/usr/bin/time sudo cmd args...
```
This doesn't ask me for a password twice.

**Comment by amano-kenji** [comment]
Apparently, the right repo is https://github.com/multiplexd/doas. Closing.

**Comment by Duncaen** [comment]
The right repo is probably https://github.com/Duncaen/OpenDoas, but this works as intended, just because sudo does not enforce that by default doesn't mean its a bug in doas, this is safer and the behavior of the original doas.

**Comment by amano-kenji** [comment]
You mean your repo.

**Comment by amano-kenji** [comment]
What's the intended behavior of the original doas? I don't use OpenBSD.

**Comment by Duncaen** [comment]
That the authentication session is bound to the parent process being the same.

Here from the original author:

https://flak.tedunangst.com/post/doas-mastery

> Additionally, the authentication information includes the parent shell process ID. This means that executing doas again in a shell script will require authentication. Or, to repeat that another way, if you run a script or program of uncertain quality, it won’t be able to silently elevate privileges. (That’s the theory anyway. In practice the check leaves quite some wiggle room.)

> You mean your repo.

Check if your package manager has a homepage for the package, its most likely my repo.
